// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: implementation/implementation.proto

package implementation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhichEnvVar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WhichEnvVar string `protobuf:"bytes,1,opt,name=whichEnvVar,proto3" json:"whichEnvVar,omitempty"`
}

func (x *WhichEnvVar) Reset() {
	*x = WhichEnvVar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_implementation_implementation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhichEnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhichEnvVar) ProtoMessage() {}

func (x *WhichEnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_implementation_implementation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhichEnvVar.ProtoReflect.Descriptor instead.
func (*WhichEnvVar) Descriptor() ([]byte, []int) {
	return file_implementation_implementation_proto_rawDescGZIP(), []int{0}
}

func (x *WhichEnvVar) GetWhichEnvVar() string {
	if x != nil {
		return x.WhichEnvVar
	}
	return ""
}

type EnvVar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvVar string `protobuf:"bytes,1,opt,name=envVar,proto3" json:"envVar,omitempty"`
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_implementation_implementation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_implementation_implementation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_implementation_implementation_proto_rawDescGZIP(), []int{1}
}

func (x *EnvVar) GetEnvVar() string {
	if x != nil {
		return x.EnvVar
	}
	return ""
}

var File_implementation_implementation_proto protoreflect.FileDescriptor

var file_implementation_implementation_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x0b, 0x77, 0x68, 0x69, 0x63, 0x68, 0x45, 0x6e,
	0x76, 0x56, 0x61, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x68, 0x69, 0x63, 0x68, 0x45, 0x6e, 0x76,
	0x56, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x68, 0x69, 0x63, 0x68,
	0x45, 0x6e, 0x76, 0x56, 0x61, 0x72, 0x22, 0x20, 0x0a, 0x06, 0x65, 0x6e, 0x76, 0x56, 0x61, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x76, 0x56, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x6e, 0x76, 0x56, 0x61, 0x72, 0x32, 0x4f, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x45,
	0x6e, 0x76, 0x56, 0x61, 0x72, 0x12, 0x42, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x56,
	0x61, 0x72, 0x12, 0x1b, 0x2e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x77, 0x68, 0x69, 0x63, 0x68, 0x45, 0x6e, 0x76, 0x56, 0x61, 0x72, 0x1a,
	0x16, 0x2e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x65, 0x6e, 0x76, 0x56, 0x61, 0x72, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_implementation_implementation_proto_rawDescOnce sync.Once
	file_implementation_implementation_proto_rawDescData = file_implementation_implementation_proto_rawDesc
)

func file_implementation_implementation_proto_rawDescGZIP() []byte {
	file_implementation_implementation_proto_rawDescOnce.Do(func() {
		file_implementation_implementation_proto_rawDescData = protoimpl.X.CompressGZIP(file_implementation_implementation_proto_rawDescData)
	})
	return file_implementation_implementation_proto_rawDescData
}

var file_implementation_implementation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_implementation_implementation_proto_goTypes = []interface{}{
	(*WhichEnvVar)(nil), // 0: implementation.whichEnvVar
	(*EnvVar)(nil),      // 1: implementation.envVar
}
var file_implementation_implementation_proto_depIdxs = []int32{
	0, // 0: implementation.GetEnvVar.GetEnvVar:input_type -> implementation.whichEnvVar
	1, // 1: implementation.GetEnvVar.GetEnvVar:output_type -> implementation.envVar
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_implementation_implementation_proto_init() }
func file_implementation_implementation_proto_init() {
	if File_implementation_implementation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_implementation_implementation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhichEnvVar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_implementation_implementation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvVar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_implementation_implementation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_implementation_implementation_proto_goTypes,
		DependencyIndexes: file_implementation_implementation_proto_depIdxs,
		MessageInfos:      file_implementation_implementation_proto_msgTypes,
	}.Build()
	File_implementation_implementation_proto = out.File
	file_implementation_implementation_proto_rawDesc = nil
	file_implementation_implementation_proto_goTypes = nil
	file_implementation_implementation_proto_depIdxs = nil
}
